// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("QueryableProvider.DesignTime")>]
[<assembly: AssemblyProductAttribute("QueryableProvider")>]
[<assembly: AssemblyDescriptionAttribute("This library is for the .NET platform implementing QueryableProvider.")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "QueryableProvider.DesignTime"
    let [<Literal>] AssemblyProduct = "QueryableProvider"
    let [<Literal>] AssemblyDescription = "This library is for the .NET platform implementing QueryableProvider."
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
